#pragma once

/* taken from src/app/zap-templates/zcl/data-model/chip/matter-devices.xml */

#define MATTER_DEVICE_ID_AIR_QUALITY_SENSOR     (0x002C)
#define MATTER_DEVICE_ID_CONTACT_SENSOR         (0x0015)
#define MATTER_DEVICE_ID_DOOR_LOCK              (0x000A)
#define MATTER_DEVICE_ID_ELECTRICAL_SENSOR      (0x0510)
#define MATTER_DEVICE_ID_EXTENDED_COLOR_LIGHT   (0x010D)
#define MATTER_DEVICE_ID_HUMIDITY_SENSOR        (0x0307)
#define MATTER_DEVICE_ID_LIGHT_SENSOR           (0x0106)
#define MATTER_DEVICE_ID_OCCUPANCY_SENSOR       (0x0107)
#define MATTER_DEVICE_ID_TEMPERATURE_SENSOR     (0x0302)
#define MATTER_DEVICE_ID_WINDOW_COVERING        (0x0202)
